/** THIS IS AN AUTOMATICALLY GENERATED FILE.  DO NOT MODIFY
 * BY HAND!!
 *
 * Generated by lcm-gen
 **/

#include <string.h>
#include "blicycle_sound_packet_t.h"

static int __blicycle_sound_packet_t_hash_computed;
static int64_t __blicycle_sound_packet_t_hash;

int64_t __blicycle_sound_packet_t_hash_recursive(const __lcm_hash_ptr *p)
{
    const __lcm_hash_ptr *fp;
    for (fp = p; fp != NULL; fp = fp->parent)
        if (fp->v == __blicycle_sound_packet_t_get_hash)
            return 0;

    const __lcm_hash_ptr cp = { p, (void*)__blicycle_sound_packet_t_get_hash };
    (void) cp;

    int64_t hash = 0xcdfad2258b15661eLL
         + __int16_t_hash_recursive(&cp)
         + __boolean_hash_recursive(&cp)
         + __boolean_hash_recursive(&cp)
         + __int8_t_hash_recursive(&cp)
        ;

    return (hash<<1) + ((hash>>63)&1);
}

int64_t __blicycle_sound_packet_t_get_hash(void)
{
    if (!__blicycle_sound_packet_t_hash_computed) {
        __blicycle_sound_packet_t_hash = __blicycle_sound_packet_t_hash_recursive(NULL);
        __blicycle_sound_packet_t_hash_computed = 1;
    }

    return __blicycle_sound_packet_t_hash;
}

int __blicycle_sound_packet_t_encode_array(void *buf, int offset, int maxlen, const blicycle_sound_packet_t *p, int elements)
{
    int pos = 0, thislen, element;

    for (element = 0; element < elements; element++) {

        thislen = __int16_t_encode_array(buf, offset + pos, maxlen - pos, &(p[element].sound_id), 1);
        if (thislen < 0) return thislen; else pos += thislen;

        thislen = __boolean_encode_array(buf, offset + pos, maxlen - pos, &(p[element].newSound), 1);
        if (thislen < 0) return thislen; else pos += thislen;

        thislen = __boolean_encode_array(buf, offset + pos, maxlen - pos, &(p[element].solo), 1);
        if (thislen < 0) return thislen; else pos += thislen;

        thislen = __int8_t_encode_array(buf, offset + pos, maxlen - pos, &(p[element].fade), 1);
        if (thislen < 0) return thislen; else pos += thislen;

    }
    return pos;
}

int blicycle_sound_packet_t_encode(void *buf, int offset, int maxlen, const blicycle_sound_packet_t *p)
{
    int pos = 0, thislen;
    int64_t hash = __blicycle_sound_packet_t_get_hash();

    thislen = __int64_t_encode_array(buf, offset + pos, maxlen - pos, &hash, 1);
    if (thislen < 0) return thislen; else pos += thislen;

    thislen = __blicycle_sound_packet_t_encode_array(buf, offset + pos, maxlen - pos, p, 1);
    if (thislen < 0) return thislen; else pos += thislen;

    return pos;
}

int __blicycle_sound_packet_t_encoded_array_size(const blicycle_sound_packet_t *p, int elements)
{
    int size = 0, element;
    for (element = 0; element < elements; element++) {

        size += __int16_t_encoded_array_size(&(p[element].sound_id), 1);

        size += __boolean_encoded_array_size(&(p[element].newSound), 1);

        size += __boolean_encoded_array_size(&(p[element].solo), 1);

        size += __int8_t_encoded_array_size(&(p[element].fade), 1);

    }
    return size;
}

int blicycle_sound_packet_t_encoded_size(const blicycle_sound_packet_t *p)
{
    return 8 + __blicycle_sound_packet_t_encoded_array_size(p, 1);
}

int __blicycle_sound_packet_t_decode_array(const void *buf, int offset, int maxlen, blicycle_sound_packet_t *p, int elements)
{
    int pos = 0, thislen, element;

    for (element = 0; element < elements; element++) {

        thislen = __int16_t_decode_array(buf, offset + pos, maxlen - pos, &(p[element].sound_id), 1);
        if (thislen < 0) return thislen; else pos += thislen;

        thislen = __boolean_decode_array(buf, offset + pos, maxlen - pos, &(p[element].newSound), 1);
        if (thislen < 0) return thislen; else pos += thislen;

        thislen = __boolean_decode_array(buf, offset + pos, maxlen - pos, &(p[element].solo), 1);
        if (thislen < 0) return thislen; else pos += thislen;

        thislen = __int8_t_decode_array(buf, offset + pos, maxlen - pos, &(p[element].fade), 1);
        if (thislen < 0) return thislen; else pos += thislen;

    }
    return pos;
}

int __blicycle_sound_packet_t_decode_array_cleanup(blicycle_sound_packet_t *p, int elements)
{
    int element;
    for (element = 0; element < elements; element++) {

        __int16_t_decode_array_cleanup(&(p[element].sound_id), 1);

        __boolean_decode_array_cleanup(&(p[element].newSound), 1);

        __boolean_decode_array_cleanup(&(p[element].solo), 1);

        __int8_t_decode_array_cleanup(&(p[element].fade), 1);

    }
    return 0;
}

int blicycle_sound_packet_t_decode(const void *buf, int offset, int maxlen, blicycle_sound_packet_t *p)
{
    int pos = 0, thislen;
    int64_t hash = __blicycle_sound_packet_t_get_hash();

    int64_t this_hash;
    thislen = __int64_t_decode_array(buf, offset + pos, maxlen - pos, &this_hash, 1);
    if (thislen < 0) return thislen; else pos += thislen;
    if (this_hash != hash) return -1;

    thislen = __blicycle_sound_packet_t_decode_array(buf, offset + pos, maxlen - pos, p, 1);
    if (thislen < 0) return thislen; else pos += thislen;

    return pos;
}

int blicycle_sound_packet_t_decode_cleanup(blicycle_sound_packet_t *p)
{
    return __blicycle_sound_packet_t_decode_array_cleanup(p, 1);
}

int __blicycle_sound_packet_t_clone_array(const blicycle_sound_packet_t *p, blicycle_sound_packet_t *q, int elements)
{
    int element;
    for (element = 0; element < elements; element++) {

        __int16_t_clone_array(&(p[element].sound_id), &(q[element].sound_id), 1);

        __boolean_clone_array(&(p[element].newSound), &(q[element].newSound), 1);

        __boolean_clone_array(&(p[element].solo), &(q[element].solo), 1);

        __int8_t_clone_array(&(p[element].fade), &(q[element].fade), 1);

    }
    return 0;
}

blicycle_sound_packet_t *blicycle_sound_packet_t_copy(const blicycle_sound_packet_t *p)
{
    blicycle_sound_packet_t *q = (blicycle_sound_packet_t*) malloc(sizeof(blicycle_sound_packet_t));
    __blicycle_sound_packet_t_clone_array(p, q, 1);
    return q;
}

void blicycle_sound_packet_t_destroy(blicycle_sound_packet_t *p)
{
    __blicycle_sound_packet_t_decode_array_cleanup(p, 1);
    free(p);
}

int blicycle_sound_packet_t_publish(lcm_t *lc, const char *channel, const blicycle_sound_packet_t *p)
{
      int max_data_size = blicycle_sound_packet_t_encoded_size (p);
      uint8_t *buf = (uint8_t*) malloc (max_data_size);
      if (!buf) return -1;
      int data_size = blicycle_sound_packet_t_encode (buf, 0, max_data_size, p);
      if (data_size < 0) {
          free (buf);
          return data_size;
      }
      int status = lcm_publish (lc, channel, buf, data_size);
      free (buf);
      return status;
}

struct _blicycle_sound_packet_t_subscription_t {
    blicycle_sound_packet_t_handler_t user_handler;
    void *userdata;
    lcm_subscription_t *lc_h;
};
static
void blicycle_sound_packet_t_handler_stub (const lcm_recv_buf_t *rbuf,
                            const char *channel, void *userdata)
{
    int status;
    blicycle_sound_packet_t p;
    memset(&p, 0, sizeof(blicycle_sound_packet_t));
    status = blicycle_sound_packet_t_decode (rbuf->data, 0, rbuf->data_size, &p);
    if (status < 0) {
        fprintf (stderr, "error %d decoding blicycle_sound_packet_t!!!\n", status);
        return;
    }

    blicycle_sound_packet_t_subscription_t *h = (blicycle_sound_packet_t_subscription_t*) userdata;
    h->user_handler (rbuf, channel, &p, h->userdata);

    blicycle_sound_packet_t_decode_cleanup (&p);
}

blicycle_sound_packet_t_subscription_t* blicycle_sound_packet_t_subscribe (lcm_t *lcm,
                    const char *channel,
                    blicycle_sound_packet_t_handler_t f, void *userdata)
{
    blicycle_sound_packet_t_subscription_t *n = (blicycle_sound_packet_t_subscription_t*)
                       malloc(sizeof(blicycle_sound_packet_t_subscription_t));
    n->user_handler = f;
    n->userdata = userdata;
    n->lc_h = lcm_subscribe (lcm, channel,
                                 blicycle_sound_packet_t_handler_stub, n);
    if (n->lc_h == NULL) {
        fprintf (stderr,"couldn't reg blicycle_sound_packet_t LCM handler!\n");
        free (n);
        return NULL;
    }
    return n;
}

int blicycle_sound_packet_t_subscription_set_queue_capacity (blicycle_sound_packet_t_subscription_t* subs,
                              int num_messages)
{
    return lcm_subscription_set_queue_capacity (subs->lc_h, num_messages);
}

int blicycle_sound_packet_t_unsubscribe(lcm_t *lcm, blicycle_sound_packet_t_subscription_t* hid)
{
    int status = lcm_unsubscribe (lcm, hid->lc_h);
    if (0 != status) {
        fprintf(stderr,
           "couldn't unsubscribe blicycle_sound_packet_t_handler %p!\n", hid);
        return -1;
    }
    free (hid);
    return 0;
}

