/** THIS IS AN AUTOMATICALLY GENERATED FILE.  DO NOT MODIFY
 * BY HAND!!
 *
 * Generated by lcm-gen
 **/

#include <stdint.h>
#include <stdlib.h>
#include <lcm/lcm_coretypes.h>
#include <lcm/lcm.h>

#ifndef _blicycle_sound_packet_t_h
#define _blicycle_sound_packet_t_h

#ifdef __cplusplus
extern "C" {
#endif

typedef struct _blicycle_sound_packet_t blicycle_sound_packet_t;
struct _blicycle_sound_packet_t
{
    int16_t    sound_id;
    int8_t     newSound;
    int8_t     solo;
    int8_t     fade;
};

blicycle_sound_packet_t   *blicycle_sound_packet_t_copy(const blicycle_sound_packet_t *p);
void blicycle_sound_packet_t_destroy(blicycle_sound_packet_t *p);

typedef struct _blicycle_sound_packet_t_subscription_t blicycle_sound_packet_t_subscription_t;
typedef void(*blicycle_sound_packet_t_handler_t)(const lcm_recv_buf_t *rbuf,
             const char *channel, const blicycle_sound_packet_t *msg, void *user);

int blicycle_sound_packet_t_publish(lcm_t *lcm, const char *channel, const blicycle_sound_packet_t *p);
blicycle_sound_packet_t_subscription_t* blicycle_sound_packet_t_subscribe(lcm_t *lcm, const char *channel, blicycle_sound_packet_t_handler_t f, void *userdata);
int blicycle_sound_packet_t_unsubscribe(lcm_t *lcm, blicycle_sound_packet_t_subscription_t* hid);
int blicycle_sound_packet_t_subscription_set_queue_capacity(blicycle_sound_packet_t_subscription_t* subs,
                              int num_messages);


int  blicycle_sound_packet_t_encode(void *buf, int offset, int maxlen, const blicycle_sound_packet_t *p);
int  blicycle_sound_packet_t_decode(const void *buf, int offset, int maxlen, blicycle_sound_packet_t *p);
int  blicycle_sound_packet_t_decode_cleanup(blicycle_sound_packet_t *p);
int  blicycle_sound_packet_t_encoded_size(const blicycle_sound_packet_t *p);

// LCM support functions. Users should not call these
int64_t __blicycle_sound_packet_t_get_hash(void);
int64_t __blicycle_sound_packet_t_hash_recursive(const __lcm_hash_ptr *p);
int     __blicycle_sound_packet_t_encode_array(void *buf, int offset, int maxlen, const blicycle_sound_packet_t *p, int elements);
int     __blicycle_sound_packet_t_decode_array(const void *buf, int offset, int maxlen, blicycle_sound_packet_t *p, int elements);
int     __blicycle_sound_packet_t_decode_array_cleanup(blicycle_sound_packet_t *p, int elements);
int     __blicycle_sound_packet_t_encoded_array_size(const blicycle_sound_packet_t *p, int elements);
int     __blicycle_sound_packet_t_clone_array(const blicycle_sound_packet_t *p, blicycle_sound_packet_t *q, int elements);

#ifdef __cplusplus
}
#endif

#endif
