/* LCM type definition class file
 * This file was automatically generated by lcm-gen
 * DO NOT MODIFY BY HAND!!!!
 */

package yei;
 
import java.io.*;
import java.util.*;
import lcm.lcm.*;
 
public final class imu_t implements lcm.lcm.LCMEncodable
{
    public long utime;
    public double linear_acceleration[];
    public double angular_velocity[];
    public double orientation[];
 
    public imu_t()
    {
        linear_acceleration = new double[3];
        angular_velocity = new double[3];
        orientation = new double[4];
    }
 
    public static final long LCM_FINGERPRINT;
    public static final long LCM_FINGERPRINT_BASE = 0xec930eca85dfe2d5L;
 
    static {
        LCM_FINGERPRINT = _hashRecursive(new ArrayList<Class<?>>());
    }
 
    public static long _hashRecursive(ArrayList<Class<?>> classes)
    {
        if (classes.contains(yei.imu_t.class))
            return 0L;
 
        classes.add(yei.imu_t.class);
        long hash = LCM_FINGERPRINT_BASE
            ;
        classes.remove(classes.size() - 1);
        return (hash<<1) + ((hash>>63)&1);
    }
 
    public void encode(DataOutput outs) throws IOException
    {
        outs.writeLong(LCM_FINGERPRINT);
        _encodeRecursive(outs);
    }
 
    public void _encodeRecursive(DataOutput outs) throws IOException
    {
        outs.writeLong(this.utime); 
 
        for (int a = 0; a < 3; a++) {
            outs.writeDouble(this.linear_acceleration[a]); 
        }
 
        for (int a = 0; a < 3; a++) {
            outs.writeDouble(this.angular_velocity[a]); 
        }
 
        for (int a = 0; a < 4; a++) {
            outs.writeDouble(this.orientation[a]); 
        }
 
    }
 
    public imu_t(byte[] data) throws IOException
    {
        this(new LCMDataInputStream(data));
    }
 
    public imu_t(DataInput ins) throws IOException
    {
        if (ins.readLong() != LCM_FINGERPRINT)
            throw new IOException("LCM Decode error: bad fingerprint");
 
        _decodeRecursive(ins);
    }
 
    public static yei.imu_t _decodeRecursiveFactory(DataInput ins) throws IOException
    {
        yei.imu_t o = new yei.imu_t();
        o._decodeRecursive(ins);
        return o;
    }
 
    public void _decodeRecursive(DataInput ins) throws IOException
    {
        this.utime = ins.readLong();
 
        this.linear_acceleration = new double[(int) 3];
        for (int a = 0; a < 3; a++) {
            this.linear_acceleration[a] = ins.readDouble();
        }
 
        this.angular_velocity = new double[(int) 3];
        for (int a = 0; a < 3; a++) {
            this.angular_velocity[a] = ins.readDouble();
        }
 
        this.orientation = new double[(int) 4];
        for (int a = 0; a < 4; a++) {
            this.orientation[a] = ins.readDouble();
        }
 
    }
 
    public yei.imu_t copy()
    {
        yei.imu_t outobj = new yei.imu_t();
        outobj.utime = this.utime;
 
        outobj.linear_acceleration = new double[(int) 3];
        System.arraycopy(this.linear_acceleration, 0, outobj.linear_acceleration, 0, 3); 
        outobj.angular_velocity = new double[(int) 3];
        System.arraycopy(this.angular_velocity, 0, outobj.angular_velocity, 0, 3); 
        outobj.orientation = new double[(int) 4];
        System.arraycopy(this.orientation, 0, outobj.orientation, 0, 4); 
        return outobj;
    }
 
}

