/* LCM type definition class file
 * This file was automatically generated by lcm-gen
 * DO NOT MODIFY BY HAND!!!!
 */

package blicycle;
 
import java.io.*;
import java.util.*;
import lcm.lcm.*;
 
public final class blicycle_packet_t implements lcm.lcm.LCMEncodable
{
    public long timestamp;
    public int lock;
    public double delta;
    public byte lane;
    public byte totalLanes;
    public double phi;
 
    public blicycle_packet_t()
    {
    }
 
    public static final long LCM_FINGERPRINT;
    public static final long LCM_FINGERPRINT_BASE = 0x054b56d66e61f950L;
 
    static {
        LCM_FINGERPRINT = _hashRecursive(new ArrayList<Class<?>>());
    }
 
    public static long _hashRecursive(ArrayList<Class<?>> classes)
    {
        if (classes.contains(blicycle.blicycle_packet_t.class))
            return 0L;
 
        classes.add(blicycle.blicycle_packet_t.class);
        long hash = LCM_FINGERPRINT_BASE
            ;
        classes.remove(classes.size() - 1);
        return (hash<<1) + ((hash>>63)&1);
    }
 
    public void encode(DataOutput outs) throws IOException
    {
        outs.writeLong(LCM_FINGERPRINT);
        _encodeRecursive(outs);
    }
 
    public void _encodeRecursive(DataOutput outs) throws IOException
    {
        outs.writeLong(this.timestamp); 
 
        outs.writeInt(this.lock); 
 
        outs.writeDouble(this.delta); 
 
        outs.writeByte(this.lane); 
 
        outs.writeByte(this.totalLanes); 
 
        outs.writeDouble(this.phi); 
 
    }
 
    public blicycle_packet_t(byte[] data) throws IOException
    {
        this(new LCMDataInputStream(data));
    }
 
    public blicycle_packet_t(DataInput ins) throws IOException
    {
        if (ins.readLong() != LCM_FINGERPRINT)
            throw new IOException("LCM Decode error: bad fingerprint");
 
        _decodeRecursive(ins);
    }
 
    public static blicycle.blicycle_packet_t _decodeRecursiveFactory(DataInput ins) throws IOException
    {
        blicycle.blicycle_packet_t o = new blicycle.blicycle_packet_t();
        o._decodeRecursive(ins);
        return o;
    }
 
    public void _decodeRecursive(DataInput ins) throws IOException
    {
        this.timestamp = ins.readLong();
 
        this.lock = ins.readInt();
 
        this.delta = ins.readDouble();
 
        this.lane = ins.readByte();
 
        this.totalLanes = ins.readByte();
 
        this.phi = ins.readDouble();
 
    }
 
    public blicycle.blicycle_packet_t copy()
    {
        blicycle.blicycle_packet_t outobj = new blicycle.blicycle_packet_t();
        outobj.timestamp = this.timestamp;
 
        outobj.lock = this.lock;
 
        outobj.delta = this.delta;
 
        outobj.lane = this.lane;
 
        outobj.totalLanes = this.totalLanes;
 
        outobj.phi = this.phi;
 
        return outobj;
    }
 
}

